version: 2
jobs:
  maven-build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: 
          name: mvn build package running 
          command: mvn clean package
